export const products = [
  {
    id: 1,
    name: 'Shahi Gulab',
    nameHindi: 'शाही गुलाब',
    subtitle: 'Royal Rose',
    description: 'The aristocratic essence of red roses harvested at dawn — a regal fragrance for sacred offerings.',
    category: 'Floral',
    theme: {
      primary: '#8B1A1A',
      secondary: '#C4607A',
      accent: '#E8A4B8',
      bg: 'linear-gradient(135deg, #3D0B0B 0%, #8B1A1A 50%, #5B0A0A 100%)',
      glow: 'rgba(196,96,122,0.5)',
    },
    emoji: '🌹',
    notes: ['Fresh Rose', 'Woody Base', 'Musk'],
    intensity: 85,
    mood: 'Devotional',
  },
  {
    id: 2,
    name: 'Phulwari',
    nameHindi: 'फुलवारी',
    subtitle: 'Garden of Flowers',
    description: 'A lush garden bouquet of seasonal blooms — jasmine, marigold, and champa in perfect harmony.',
    category: 'Floral',
    theme: {
      primary: '#7B3F7B',
      secondary: '#B06AB3',
      accent: '#E8A4B8',
      bg: 'linear-gradient(135deg, #2D0F2D 0%, #7B3F7B 50%, #4A0F4A 100%)',
      glow: 'rgba(176,106,179,0.5)',
    },
    emoji: '🌸',
    notes: ['Jasmine', 'Marigold', 'Champa'],
    intensity: 75,
    mood: 'Joyful',
  },
  {
    id: 3,
    name: 'Raat Rani',
    nameHindi: 'रात रानी',
    subtitle: 'Queen of the Night',
    description: 'Blooming only after dusk, this mysterious night-queen fragrance fills the air with intoxicating white florals.',
    category: 'Nocturnal',
    theme: {
      primary: '#1A1A5C',
      secondary: '#3A3A8C',
      accent: '#A4A4E8',
      bg: 'linear-gradient(135deg, #050514 0%, #1A1A5C 60%, #0A0A30 100%)',
      glow: 'rgba(100,100,200,0.5)',
    },
    emoji: '🌙',
    notes: ['Night Jasmine', 'White Musk', 'Moonlit Dew'],
    intensity: 90,
    mood: 'Mystical',
  },
  {
    id: 4,
    name: 'Dev Darshan',
    nameHindi: 'देव दर्शन',
    subtitle: 'Divine Vision',
    description: 'Sacred sandalwood and camphor — the quintessential fragrance for temple rituals and divine blessings.',
    category: 'Sacred',
    theme: {
      primary: '#7B5A1A',
      secondary: '#D4AF37',
      accent: '#F0D060',
      bg: 'linear-gradient(135deg, #3D2B0B 0%, #7B5A1A 50%, #4A3508 100%)',
      glow: 'rgba(212,175,55,0.6)',
    },
    emoji: '🕉️',
    notes: ['Sandalwood', 'Camphor', 'Sacred Resins'],
    intensity: 80,
    mood: 'Spiritual',
  },
  {
    id: 5,
    name: 'Jasmine',
    nameHindi: 'जैस्मिन',
    subtitle: 'Pure Jasmine',
    description: 'The classic jasmine — fresh, clean, and intoxicatingly sweet. Perfect for morning prayers.',
    category: 'Floral',
    theme: {
      primary: '#3A5C3A',
      secondary: '#5A8C5A',
      accent: '#A4E8A4',
      bg: 'linear-gradient(135deg, #0A1F0A 0%, #1A5C1A 50%, #0F3A0F 100%)',
      glow: 'rgba(90,140,90,0.5)',
    },
    emoji: '🌿',
    notes: ['Jasmine Absolute', 'Green Notes', 'Light Musk'],
    intensity: 70,
    mood: 'Fresh & Pure',
  },
  {
    id: 6,
    name: 'Guggal',
    nameHindi: 'गुग्गल',
    subtitle: 'Sacred Resin',
    description: 'The ancient Ayurvedic resin — purifying, grounding, and deeply spiritual for cleansing rituals.',
    category: 'Resin',
    theme: {
      primary: '#5C3A1A',
      secondary: '#8C6040',
      accent: '#E8C090',
      bg: 'linear-gradient(135deg, #2D1A0A 0%, #5C3A1A 50%, #3A2010 100%)',
      glow: 'rgba(140,96,64,0.5)',
    },
    emoji: '🌿',
    notes: ['Myrrh Resin', 'Earthy', 'Balsamic Wood'],
    intensity: 95,
    mood: 'Purifying',
  },
  {
    id: 7,
    name: 'Divya Chandan',
    nameHindi: 'दिव्य चंदन',
    subtitle: 'Divine Sandalwood',
    description: 'Pure Mysore sandalwood essence — creamy, warm, and heavenly, fit for the most sacred ceremonies.',
    category: 'Sacred',
    theme: {
      primary: '#7B5A2A',
      secondary: '#C49030',
      accent: '#F0C878',
      bg: 'linear-gradient(135deg, #3D2B10 0%, #7B5A2A 50%, #5A3A18 100%)',
      glow: 'rgba(196,144,48,0.6)',
    },
    emoji: '🪵',
    notes: ['Mysore Sandalwood', 'Vanilla', 'Cedarwood'],
    intensity: 85,
    mood: 'Serene',
  },
  {
    id: 8,
    name: 'Kevda Classic',
    nameHindi: 'केवड़ा क्लासिक',
    subtitle: 'Pandanus Flower',
    description: 'The rare kevda (pandanus) flower — exotic, sweet, and unmistakably Indian in character.',
    category: 'Exotic',
    theme: {
      primary: '#1A5C4A',
      secondary: '#2A9C7A',
      accent: '#7AE8C8',
      bg: 'linear-gradient(135deg, #0A2D22 0%, #1A5C4A 50%, #0F3A2D 100%)',
      glow: 'rgba(42,156,122,0.5)',
    },
    emoji: '🌴',
    notes: ['Kevda Absolute', 'Green Aquatic', 'Light Floral'],
    intensity: 72,
    mood: 'Exotic',
  },
  {
    id: 9,
    name: 'Rajnigandha',
    nameHindi: 'रजनीगंधा',
    subtitle: 'Tuberose',
    description: 'Heady tuberose bouquets at twilight — rich, velvety white florals beloved across Indian households.',
    category: 'Floral',
    theme: {
      primary: '#7B3A5C',
      secondary: '#B06090',
      accent: '#E8A4D0',
      bg: 'linear-gradient(135deg, #3D1A2D 0%, #7B3A5C 50%, #4A2040 100%)',
      glow: 'rgba(176,96,144,0.5)',
    },
    emoji: '🌷',
    notes: ['Tuberose', 'Powdery Musk', 'Lily'],
    intensity: 88,
    mood: 'Romantic',
  },
  {
    id: 10,
    name: 'Kasturi',
    nameHindi: 'कस्तूरी',
    subtitle: 'Royal Musk',
    description: 'Inspired by the royal musk of the Himalayan deer — warm, animalic, and deeply sensual.',
    category: 'Musk',
    theme: {
      primary: '#5C2A1A',
      secondary: '#9C5040',
      accent: '#E8A090',
      bg: 'linear-gradient(135deg, #2D1008 0%, #5C2A1A 50%, #3A1810 100%)',
      glow: 'rgba(156,80,64,0.5)',
    },
    emoji: '🦌',
    notes: ['White Musk', 'Amber', 'Warm Resins'],
    intensity: 92,
    mood: 'Sensual',
  },
  {
    id: 11,
    name: 'Lavender',
    nameHindi: 'लैवेंडर',
    subtitle: 'French Lavender',
    description: 'Cool, calming French lavender fields — ideal for meditation, sleep, and peace of mind.',
    category: 'Herbal',
    theme: {
      primary: '#4A2A6B',
      secondary: '#7A5AAB',
      accent: '#C4A4E8',
      bg: 'linear-gradient(135deg, #1F0A30 0%, #4A2A6B 50%, #2D1540 100%)',
      glow: 'rgba(122,90,171,0.5)',
    },
    emoji: '💜',
    notes: ['True Lavender', 'Eucalyptus', 'Soft Musk'],
    intensity: 65,
    mood: 'Calming',
  },
  {
    id: 12,
    name: 'Sugandhit',
    nameHindi: 'सुगंधित',
    subtitle: 'The Signature',
    description: 'Our signature blend — a masterpiece of rare florals, sacred resins, and aged sandalwood.',
    category: 'Signature',
    theme: {
      primary: '#7B1C1C',
      secondary: '#D4AF37',
      accent: '#F0D060',
      bg: 'linear-gradient(135deg, #1A0505 0%, #7B1C1C 30%, #3D2B08 70%, #1A0505 100%)',
      glow: 'rgba(212,175,55,0.7)',
    },
    emoji: '✨',
    notes: ['Rose', 'Oud', 'Sandalwood', 'Saffron'],
    intensity: 100,
    mood: 'Transcendent',
  },
];
